cat << 'EOF' > ~/.config/kitty/userprefs.conf
# Enable the splits layout
enabled_layouts splits,stack

# Create a new window to the right (Vertical split)
map ctrl+shift+b launch --location=vsplit --cwd=current

# Create a new window below (Horizontal split)
map ctrl+shift+h launch --location=hsplit --cwd=current

#save current session
map ctrl+shift+s save_as_session --use-foreground-process --relocatable

#map ctrl+shift+o launch --type=tab --session "/home/cyberbee/bun dev print"


allow_remote_control yes

#EOF
